<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01_ProviderSetup</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>5f2941a6-1d00-42d6-8048-ee358106af83</testSuiteGuid>
   <testCaseLink>
      <guid>c2314342-39f1-41ba-b289-cee2f7015653</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC01_VerifyOrganizationNameInManageProviderContract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>f97d2ff4-6154-4dfc-8ae2-dd820328de85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC02_VerifyRegionIsDisplayedBasedOnTheUserRoleAccessPermissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60400d79-4988-4aae-bcbc-90a85318303a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a7a0b2e7-21c9-42bc-abe5-6dbbb5a443f4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>112fdea2-db9b-44d7-8cb5-10081588ebb3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>424bbe63-738b-47b3-987a-48da20b3b39e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC04_VerifyProviderWebServiceAfterClickingADDCONTRACT</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4da19ff6-66c6-46ab-ae50-b800646930e8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>fc791fc3-4c1a-489c-8130-e970b151c222</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC05_VerifyTotalFacilityCount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>46641912-b2d2-458c-9571-b44bf9886565</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC06_VerifyClearButtonFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d40f665-c4ff-4ef1-bf6e-dc1d73768d08</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>02e289f0-a5a7-4358-979f-72ba51c4caed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ec9636b6-747a-41cc-bd08-5256c7ce9b28</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b2569a7c-4780-4e50-a26c-1942612a0440</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>baba68f0-36d8-49e5-bf08-d5d6a5e120df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>31c29e8c-b250-416c-8106-98077f4e92cd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9530e35-dd58-4014-b126-09e6bab057de</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC07_VerifyGetContractsButtonFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bc9c181-f602-4a04-afff-fb3477c083a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a0844fb-5169-47a4-a47c-2bbdd340f6cc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9a6d3b9f-826f-4028-a9d9-c1ab6c1e9031</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC08_VerifyUniversalSearchFunctionality</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d9be8e7a-1401-4404-b596-8e6d8e6d673d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0191f9bb-ad05-46d0-bd8c-b5feb4fa284d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC09_VerifyProviderIDWebService</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81a73572-acfc-4fa7-b36f-58fea684f511</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed95fa62-57d6-483a-be34-6e3edef2abd5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC10_VerifyProviderDetailsInManageProviderContractPage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3fd12d07-da10-4c9c-b57c-c740bfac785e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>17c0a8fa-d947-4f5e-895d-ff94b8a95604</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC11_VerifyCurrentYearDropDownField</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e24b512e-6034-4455-8219-82bfd6ea07ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fd3c4c7-0508-45e6-b602-0f40e9193ef6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b9f88232-8ab0-43cc-b661-1c40fd5513d5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2ba0198e-4444-4576-8c04-20724fe75970</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC12_VerifyContractFacilityCount</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddca282d-7564-4708-8586-55a2ca95e337</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>943e5ad0-fa1b-42dd-bded-e1095a0e6117</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC13_VerifyDefaultCostCenterAndSpecialtyAfterAddingContractTab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eef71aca-51e7-4e25-86de-22452f2a3fe3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4b0612d-f559-410f-ac6d-332dbe66cd24</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14a6d42f-2d26-4fbb-8c0b-38e479eb637f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bee88311-be59-4dc4-86a0-e9b24a6f2033</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>90465df0-b64b-4888-8988-db34d3ccfd15</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC14_VerifyCostCenterTabs</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db42ba2-3157-40e2-bcb0-7cceba76783f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>013224ef-a17a-48bd-90df-b43c00f90a76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e89cc280-c880-4069-8755-8839c5992200</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b2f4608-9069-4e77-a700-0b60c106c4fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bafc6617-e038-4095-83f5-838468cd2087</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC15_VerifyPayCycle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc921bd1-246f-4db8-935f-b3789aa66fb5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aa29b3cd-10e6-4e95-8132-fc485cac30f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9686fdfd-ef27-40fc-8174-e9563cf2a137</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1eb41c9a-e058-4063-a7dc-588dddd3237f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ce09c1d7-11cc-4b5d-98dc-fc57cd39d69d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC16_VerifyPayElementDefaultStartAndEndDate</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2da46d60-7d08-4fd6-9444-df27c91a9c45</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>52388229-0077-4561-a959-0cc3b488284a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03d43f2e-2b5d-4eca-8a8b-f96e8eabd0ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9dc0cc7f-e87b-4354-943e-25684b8632f6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6c5f745-a3b9-42e6-8a63-263cae34d2c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fba33a-701c-4177-a0b8-9a1fc8f908ba</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd7197fb-d6a5-4024-8184-a3578c78cd68</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4adfe1f0-2f0b-41eb-9284-735a5c1ad48d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC17_VerifyPayElementColumnMappedToCompensationModelPayElement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc5ffb1c-b87c-4c47-8f29-ebcb6237bfa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3dca8456-226d-4a76-8214-80c7b91d594b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e406b7d5-b955-462f-86c4-e3f1870e3eeb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6b11ca3c-b9af-4528-8390-bb3eec7d5553</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a48f55b4-792a-4c39-b65a-f51d067c7f86</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86e3e462-ff2b-4579-9929-ef1076a92b18</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1fe7f70a-ac7f-4a09-9fca-b4cbe226ee48</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04506804-a8a7-4c1d-b9a5-ccf65407a15d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC18_VerifyDefaultPayElementMapped</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>804cc9dd-80a5-4a3b-b1b6-52b7a5a711ec</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c55ce4fd-470b-4312-883f-4e6283ba3f53</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1d548966-2f54-46c7-b69b-9148fff8eb22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>95ff63d7-4cf0-428a-8801-2ec48acfabac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d9eaaf4-bed1-4f96-8ed3-48d9cea98e98</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb24780c-786d-4031-b288-de0496c5626c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2a059893-81ce-4449-937d-7bfe549aef25</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC19_VerifyDisplaySettings</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08458586-3626-4dfa-a2ab-1878acbf0c5b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01979fd6-2c36-4de6-8fd3-17c34d7e8b2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cce33877-2a55-46e7-97d1-e1ab6dcb8790</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49016a0e-0a5f-4b30-bb8a-8f37fe375c49</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b6a8904-4a5b-43df-8814-47eb2fc30076</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1218dcda-9eaa-4d76-aff3-4b0e59f2d359</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61bb7840-5b8a-4a94-be2e-9d401f82e29d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC20_VerifyDisplaySettingsProfiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61d4bf3d-4757-4d72-9781-d00523e35c2f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0da5e049-bef5-4387-8c7b-c901da0aa34a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>011f0764-fa3f-4aef-9c1c-186913b76f46</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d47a4429-911c-4cea-9b12-4d1d560ede9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0335a2b2-dfa3-4b27-b817-489d0a3f9ab9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>321a008b-2c69-49b5-afae-4cd2a5b9317f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9c0975ca-a39f-4714-8e37-136882c7f767</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC21_VerifyFTECategoryAddition</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0615f18-339d-40ad-884b-e9afdd2a660a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23f7ba63-982d-401b-a0b4-defa81fccac5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>37d82b25-cfef-4178-9ca2-36d4f7893aee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d241ae-3bd5-4cea-b636-e75186e424ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d896348-e4b3-4e5d-93e8-e81e5321a248</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ad7cd2d0-524b-48da-862f-37632fad984a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f9e1cd9-024b-426c-bb6e-f196b59db98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c1f5a84-6a66-43d3-8d43-e46591ddefb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c21808cd-8956-4937-9f12-d8bee103b6c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db80851-28e1-46eb-8172-8b3a3d4e0b86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4d7cd3d0-14a3-4dc5-92b5-4533d3bea117</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC22_VerifyFTECategoryUpdation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0615f18-339d-40ad-884b-e9afdd2a660a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b4d241ae-3bd5-4cea-b636-e75186e424ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f9e1cd9-024b-426c-bb6e-f196b59db98d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c1f5a84-6a66-43d3-8d43-e46591ddefb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c21808cd-8956-4937-9f12-d8bee103b6c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9db80851-28e1-46eb-8172-8b3a3d4e0b86</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6e341eca-faba-46c4-a277-a9c690ff837f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC23_VerifySelectionOfMultipleCompensationModelInAddContractPopup</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e9813b8b-2e20-493b-88e4-970c4413526c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd209fcc-110e-46e1-ae9b-ae82e80e5356</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ddb6772-8a26-4dc3-8c96-f95c270b1735</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af0e1335-43d6-41a6-a336-bd8a4f274320</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97d63f46-1938-449c-9fd3-46ef87f39101</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73600624-ec98-4dc8-baf5-3d040c10570e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>22c1cf98-8fa6-4d9f-a17b-8848b2798498</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a915c14f-a60b-4325-b44e-4464f7f52837</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC24_VerifySelectionOfMultipleCostCenter</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3b529f4-58e5-4aee-8dfe-8ac5b1e21d13</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>505d3d70-9ae2-4ba6-8270-255e3ed238a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003e3d3e-0a1c-473c-afaf-8bbaf14f5add</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c7b4c8a-7f42-4125-88e0-e2965a899ef0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b0637b14-0d50-4f9c-8037-59291ec56b39</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>592a6fa5-e0f7-4d2e-b923-9c87a0e1447d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c0e6d7a6-a41f-4888-9592-ed1d430183d9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71ef6257-4040-4057-9ac3-70a937250e61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af4a1b75-d590-4d41-9ce8-51eee2092be8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>20c12abe-c29d-48b6-b42c-238a26c7e659</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC25_VerifyCreationOfProviderContract</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13e0afcb-2425-4fbf-9f39-32e35cbf449e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>410c25a5-e96e-4f62-94d5-67ff899972c7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9115715e-9a8a-4ba4-bd34-7e8b4e24ed21</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13759a05-2430-4c3c-ada1-c7b5804547c4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd469494-912f-4d5e-a89a-2cac69f04bc4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd772166-b98a-45d0-9b9d-df7b2d035dc6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d897f705-6c94-45bd-b81a-3347f8d08173</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e8437cf8-f6c8-4ba5-ab22-e7dff3759877</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2037ebf4-cc49-4fa5-8917-924126a612db</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/02_ManageProviderContract/MPC26_VerifyDeletionOfContractTab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7bfad2c9-5dfc-4307-8b31-9c44a85b4e25</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1677d3f4-e1b7-4cf6-a39b-4f883c26a663</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
