<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>07_ProviderEMRData_ArdentQA</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>1</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>a2e14bc5-bbe2-4e3d-b5fe-5607d30c8542</testSuiteGuid>
   <testCaseLink>
      <guid>e9243c72-3826-4580-8f5b-9bf5c44d6abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR01_ValidateProviderEMRDataUI</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>b77a282b-f258-453d-890a-8352d3ce5c06</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR02_ValidateProviderEMRDataGridUI</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ce7b2e43-98cf-40f8-a688-9d47cb29ece5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR02_ValidateProviderEMRDataGridUI</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ce7b2e43-98cf-40f8-a688-9d47cb29ece5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>393a7c37-735d-4029-ad77-b47cad5e96e3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>caad4309-f3ae-4028-8582-d694f61f5ab6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR24_ValidateFilterFunctionalitywithDifferentCombination</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>89efbf9a-a0f6-4697-b9c9-cba6ec126667</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR24_ValidateFilterFunctionalitywithDifferentCombination</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>b86c276f-9769-496a-ac8f-f99f2ff6473a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CostCenter</value>
         <variableId>7487eab8-dc71-4df9-8199-4646a5607189</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Year</value>
         <variableId>be955680-2a41-4f19-a13a-b8006940a949</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Month</value>
         <variableId>61219640-c6ff-4ef2-b37f-232a75c2fa94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ProviderName</value>
         <variableId>46017d21-574c-42b8-9f8d-e8b927120e2c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>89efbf9a-a0f6-4697-b9c9-cba6ec126667</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>UniversalSearch</value>
         <variableId>7ce8f476-3456-4f2d-a107-0005057dcc0c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5e77587b-0529-4a31-8811-11c939d353cf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR27_ValidateExportExceltoExportTheRecordsofOriginalAndProcessed</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>7ba6121a-98fa-4d6d-8ce1-79bdee419e50</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR29_ValidateDownloadFunctionalityofMissingType</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6c2713b9-548e-4476-bd21-f16d59653eb8</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR29_ValidateDownloadFunctionalityofMissingType</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>6c2713b9-548e-4476-bd21-f16d59653eb8</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>MissingType</value>
         <variableId>bcb9f431-1745-45e9-ab1a-6b5a13637155</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f50c0e15-b165-4e13-9ef9-b3f85d8c24bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR30_ValidateScrollFunctionalityWhenEMRListContainsMax500records</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d4e68a7b-adac-4285-9cae-b14a1ebae1fe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR30_ValidateScrollFunctionalityWhenEMRListContainsMax500records</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d4e68a7b-adac-4285-9cae-b14a1ebae1fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>6a9c5cff-786c-4197-beaa-6b37fb1c1bfe</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e4eb4be2-bca0-47bc-a47d-1baa60e4bfa1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR31_ValidateNavigatePagination</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bf9b2846-9ecb-461b-bf01-b551e83252f9</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR31_ValidateNavigatePagination</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bf9b2846-9ecb-461b-bf01-b551e83252f9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>3cf37f87-2d0b-4c51-9679-b8e621e20d64</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>04e03858-c089-4b0d-bea8-88c582d147a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR33_ValidateDetailsLinkshowsthewRVUSofProvider</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d8ebe853-ccb5-430d-b798-c09abccdfe83</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR33_ValidateDetailsLinkshowsthewRVUSofProvider</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d8ebe853-ccb5-430d-b798-c09abccdfe83</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>dc9c2801-f558-44fd-9272-cdb85f8d0ffd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69cfa724-e30b-40b4-9aba-156e7cbb45ea</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR34_ValidateUploadEMRFileTypeAsPerApplicableFlagSettings</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b0484c4f-25b0-4341-adb1-19e7dd5f643f</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR34_ValidateUploadEMRFileTypeAsPerApplicableFlagSettings</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>b0484c4f-25b0-4341-adb1-19e7dd5f643f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>cba8ad08-4320-4b19-90fc-6c8fad918899</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b0484c4f-25b0-4341-adb1-19e7dd5f643f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>7bb61584-b5e0-4f23-8634-53e0b1421483</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ed901321-b202-417a-991c-6db88b90b1a7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/HII/07_ProviderEMRData/EMR35_Validate DisplayOriginalEMRDataAsPerApplicableSettings</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>254840ed-659a-4288-866d-eff7b24cf5fe</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/ArdentQA/07_ProviderEMRData/td_EMR34_ValidateUploadEMRFileTypeAsPerApplicableFlagSettings</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>254840ed-659a-4288-866d-eff7b24cf5fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Region</value>
         <variableId>366af01d-aa88-45aa-a776-ca4bf6b0ab4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>254840ed-659a-4288-866d-eff7b24cf5fe</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Location</value>
         <variableId>26f896e2-fa75-4f09-871e-5c712bbc5060</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
